### ISSUE TITLE
Can't parse unicode

### ISSUE THREAD

**Issue by r-barnes** [facebook/pyre-check#401] opened 2021-03-29 03:19 UTC
I ask Pyre to type check a file including:
```
def foo(rhat=0.5, rtilde=0.2, μ=0.1, ν=0.1, T=8.0, P0=0.05, desired_dt=0.05):
```
and it returns
```
 ƛ Could not parse file at MirmiraniOster1978_single_season.py:3:30-3:30
```
It looks like it doesn't like the use of `μ` as a variable name, though that should be valid and Python 3.8.5 interprets it as such.

**Comment by JelleZijlstra** [comment] 2021-03-29 20:11
Duplicate of #254 I think

**Comment by dkgi** [comment] 2021-03-29 20:39
Will close in favor of the existing one. Our OCaml parser does not support unicode by default. We have plans to address this but they're not currently a priority :/

**Closed by dkgi** 2021-03-29 20:39 UTC
