### ISSUE TITLE
`make test` and `make python_tests` failing

### ISSUE THREAD

**Issue by theodoretliu** [facebook/pyre-check#282] opened 2020-07-21 19:51 UTC
Getting the following error on a few tests during `make test`
```
Build info: Darwin x86_64 @ Tue Jul 21 2020 (development build)
abort: no repository found in '/Users/theodoreliu/pyre-check' (.hg not found)!
Git commit: 89d2e0301cccb14b5cb8f60f8ffbe552db9c008f
dune build @install -j auto --profile dev
  serverTest alias command/test/runtest (exit 1)
(cd _build/default/command/test && ./serverTest.exe)
........Finished SQL Transaction took 0.00s
Lookup of existing rows took 541 us
Wrote 580 new rows
Updated 0 existing rows
Finished closing SQL connection took 0.00s
Writing dependency file with sqlite took 0.01s
....FUncaught exception:

  (Sys_error "Too many open files")

Raised by primitive operation at file "src/lib/ounit2/advanced/oUnitCheckEnv.ml", line 47, characters 10-23
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 80, characters 25-48
Called from file "src/lib/ounit2/advanced/oUnitTest.ml", line 130, characters 16-22
Re-raised at file "src/lib/ounit2/advanced/oUnitTest.ml", line 135, characters 6-13
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 78, characters 4-516
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 321, characters 22-72
Called from file "src/lib/ounit2/advanced/oUnitRunnerProcesses.ml", line 160, characters 10-167
Called from file "src/lib/ounit2/advanced/oUnitRunner.ml", line 526, characters 16-105
Called from file "src/lib/ounit2/advanced/oUnitUtils.ml", line 175, characters 12-15
Called from file "src/lib/ounit2/advanced/oUnitCore.ml", line 83, characters 4-59
Called from file "src/lib/ounit2/advanced/oUnitCore.ml", line 173, characters 10-55
Called from file "command/test/serverTest.ml", line 1667, characters 2-1023
E.....
==============================================================================
Error: server:13:incremental_typecheck.

File "/Users/theodoreliu/pyre-check/_build/default/command/test/oUnit-server-Theodores-MacBook-Pro.local#00.log", line 9506, characters 1-1:
Error: server:13:incremental_typecheck (in the log).

Worker stops running: Exited with code 2
------------------------------------------------------------------------------
==============================================================================
Error: server:12:incremental_dependencies.

File "/Users/theodoreliu/pyre-check/_build/default/command/test/oUnit-server-Theodores-MacBook-Pro.local#01.log", line 4712, characters 1-1:
Error: server:12:incremental_dependencies (in the log).

File "test/test.ml", line 77, characters 1-1:
Error: server:12:incremental_dependencies (in the code).

not equal
------------------------------------------------------------------------------
Ran: 19 tests in: 10.89 seconds.
FAILED: Cases: 19 Tried: 19 Errors: 1 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
make: *** [test] Error 1
```

and the following errors from `make python_tests`
```
./scripts/run-python-tests.sh
  Using interpreter at /Users/theodoreliu/.pyenv/shims/python3 with version: Python 3.7.7
  Enumerating test files:
client/tests/terminal_test.py
client/tests/project_files_monitor_test.py
client/tests/find_directories_test.py
client/tests/buck_test.py
client/tests/process_test.py
client/tests/resources_test.py
client/tests/recently_used_configurations_test.py
client/tests/analysis_directory_test.py
client/tests/configuration_monitor_test.py
client/tests/watchman_test.py
client/tests/pyre_test.py
client/tests/json_rpc_test.py
client/tests/configuration_test.py
client/tests/filesystem_test.py
client/tests/error_test.py
client/commands/tests/analyze_test.py
client/commands/tests/reporting_test.py
client/commands/tests/incremental_test.py
client/commands/tests/query_test.py
client/commands/tests/profile_test.py
client/commands/tests/start_test.py
client/commands/tests/check_test.py
client/commands/tests/kill_test.py
client/commands/tests/command_test.py
client/commands/tests/servers_test.py
client/commands/tests/restart_test.py
client/commands/tests/infer_test.py
client/commands/tests/statistics_test.py
client/commands/tests/stop_test.py
client/commands/tests/rage_test.py
client/commands/tests/initialize_test.py
client/commands/tests/persistent_test.py
  Running all tests:
test_is_capable_terminal (client.tests.terminal_test.PyreTest) ... ok
test_bad_socket (client.tests.project_files_monitor_test.MonitorTest) ... ok
test_files_cleaned_up (client.tests.project_files_monitor_test.MonitorTest) ... ok
test_restart_if_dead_when_alive (client.tests.project_files_monitor_test.MonitorTest) ... ok
test_restart_if_dead_when_dead (client.tests.project_files_monitor_test.MonitorTest) ... ok
test_socket_communication (client.tests.project_files_monitor_test.MonitorTest) ... /Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/socket.py:660: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/var/folders/q8/29hfkdt14qd1qpx4csvyzq0r0000gn/T/tmpi_w5pxg0/.pyre/server/json_server.sock>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/mock.py:1259: ResourceWarning: unclosed <socket.socket fd=9, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/var/folders/q8/29hfkdt14qd1qpx4csvyzq0r0000gn/T/tmpi_w5pxg0/.pyre/server/json_server.sock>
  return func(*args, **keywargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_socket_connection (client.tests.project_files_monitor_test.MonitorTest) ... /Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/threading.py:870: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/var/folders/q8/29hfkdt14qd1qpx4csvyzq0r0000gn/T/tmpp2rv29rn/json_server.sock>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/mock.py:1259: ResourceWarning: unclosed <socket.socket fd=9, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/var/folders/q8/29hfkdt14qd1qpx4csvyzq0r0000gn/T/tmpp2rv29rn/json_server.sock>
  return func(*args, **keywargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_subscriptions (client.tests.project_files_monitor_test.MonitorTest) ... ok
test_find_local_root (client.tests.find_directories_test.InitTest) ... ok
test_find_project_root (client.tests.find_directories_test.InitTest) ... ok
test_build_targets (client.tests.buck_test.BuckTest) ... Finished building targets.
ok
test_find_built_source_directories (client.tests.buck_test.BuckTest) ... ok
test_generate_source_directories (client.tests.buck_test.BuckTest) ... ok
test_map_normalized_targets_to_original (client.tests.buck_test.BuckTest) ... ok
test_normalize (client.tests.buck_test.BuckTest) ... ok
test_presumed_target_root (client.tests.buck_test.BuckTest) ... ok
test_query_buck_relative_paths (client.tests.buck_test.BuckTest) ... ok
test_query_buck_relative_paths_base_module (client.tests.buck_test.BuckTest) ... ok
test_get_process (client.tests.process_test.ProcessTest) ... ok
test_get_process_error (client.tests.process_test.ProcessTest) ... ok
test_get_process_file_not_found (client.tests.process_test.ProcessTest) ... ok
test_get_processes (client.tests.process_test.ProcessTest) ... ok
test_is_alive (client.tests.process_test.ProcessTest) ... ok
test_is_alive__dead (client.tests.process_test.ProcessTest) ... ok
test_is_alive__exception (client.tests.process_test.ProcessTest) ... ok
test_register (client.tests.process_test.ProcessTest) ... ok
test_register_exception (client.tests.process_test.ProcessTest) ... ok
test_find_log_directory (client.tests.resources_test.ResourcesTest) ... ok
test_add_recently_used_configuration (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_delete_cache (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_get_all_items (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_get_all_items__lock_not_acquired (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_load_items_from_file (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_load_items_from_file__json_error (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_load_items_from_file__no_existing_file (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_prompt_user_for_local_root (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_prompt_user_for_local_root__exception (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... No valid local root chosen. Quitting.
ok
test_prompt_user_for_local_root__interrupt (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... No valid local root chosen. Quitting.
ok
test_prompt_user_for_local_root__not_terminal (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_prompt_user_for_local_root__pressed_enter (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_put (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_put__lock_not_acquired (client.tests.recently_used_configurations_test.RecentlyUsedConfigurationsTest) ... ok
test_process_updated_files (client.tests.analysis_directory_test.AnalysisDirectoryTest) ... ok
test_resolve_analysis_directory (client.tests.analysis_directory_test.AnalysisDirectoryTest) ... Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
ok
test_cache_last_deleted_link (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_cleanup (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_cleanup__exception (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_directories_to_clean_up (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_fetch_cached_absolute_link_map (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_filter_root_for_buck (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_filter_root_for_nonbuck (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_get_new_deleted_and_tracked_paths_for_local_project (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_get_new_deleted_and_tracked_paths_for_root_project (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_get_project_name (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_merge (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_merge_into_paths (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_notify_about_rebuild (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_prepare (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... FAIL
test_process_rebuilt_files (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files__acquire_lock (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files__rebuild (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files_one_deleted_file (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files_one_new_file (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files_only_tracked_files (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_process_updated_files_same_file_after_deletion (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_rebuild (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... FAIL
test_resolve_analysis_directory (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... Setting up a `.pyre_configuration.local` with `pyre init --local` may reduce overhead.
Setting up a `.pyre_configuration.local` with `pyre init --local` may reduce overhead.
ok
test_resolve_filter_paths (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_should_rebuild (client.tests.analysis_directory_test.SharedAnalysisDirectoryTest) ... ok
test_daemonize (client.tests.configuration_monitor_test.MonitorTest) ... ok
test_handle_response (client.tests.configuration_monitor_test.MonitorTest) ... ok
test_run (client.tests.configuration_monitor_test.MonitorTest) ... ok
test_subscriptions (client.tests.configuration_monitor_test.MonitorTest) ... ok
test_cleanup_on_sigint (client.tests.watchman_test.SubscriberTest) ... Traceback (most recent call last):
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/unittest/mock.py", line 1259, in patched
    return func(*args, **keywargs)
  File "/Users/theodoreliu/pyre-check/client/tests/watchman_test.py", line 51, in test_cleanup_on_sigint
    subscriber.daemonize()
  File "/Users/theodoreliu/pyre-check/client/watchman.py", line 149, in daemonize
    self._run()
  File "/Users/theodoreliu/pyre-check/client/watchman.py", line 90, in _run
    with acquire_lock(lock_path, blocking=False), (
  File "/Users/theodoreliu/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/theodoreliu/pyre-check/client/tests/watchman_test.py", line 23, in send_sigint_to_self
    os.kill(os.getpid(), signal.SIGINT)
KeyboardInterrupt
make: *** [python_tests] Error 1
```

Let me know if it'd be helpful to pare down some of the errors.

**Comment by fylux** [comment] 2020-07-22 15:49
For the moment I can only add that the second line:

`abort: no repository found in '/Users/theodoreliu/pyre-check' (.hg not found)!`

Even if it says abort the code will continue all right, seems to be related with the bash script when doing:

`HG_VERSION="$(hg log -r . -T '{node}')"; then`

**Comment by theodoretliu** [comment] 2020-07-22 19:22
Yeah, that came up previously and didn't cause problems. I'm more wondering about the errors regarding "too many open files" and SQLite

**Comment by mrkmndz** [comment] 2020-07-22 19:27
Does that happen if you re-run the test?
-Mark A. Mendoza

**Comment by theodoretliu** [comment] 2020-07-22 19:37
Okay, so if I modify the `Makefile` manually and set `-j 1` in the `dune runtest` command, it actually succeeds. So apparently 8 jobs is just too many for my computer to handle. Is there something equivalent for the python tests?

**Comment by mrkmndz** [comment] 2020-07-22 19:45
I can actually reproduce the python test failure, so that's probably
something on our end.
-Mark A. Mendoza

**Comment by MaggieMoss** [comment] 2021-03-19 18:11
Closing since it seems like this has resolved - if it appears again feel free to re-open.

**Closed by MaggieMoss** 2021-03-19 18:11 UTC
