### ISSUE TITLE
Python stdlib `string.Formatter` doesn't understand `LiteralString`

### ISSUE THREAD

**Issue by dvarrazzo** [facebook/pyre-check#635] opened 2022-06-27 21:45 UTC
Hello,

I have tried to use pyre to introduce `LiteralString` in psycopg 3 codebase.

I could fix all the internal usage of LiteralString, however, several methods of  [`string.Formatter`](https://docs.python.org/3.8/library/string.html#string.Formatter) might be considered returning `LiteralString` on `LiteralString` input.

See: https://github.com/psycopg/psycopg/blob/600d6dfaf1366d2eca4486f7686c57da88f2b807/psycopg/psycopg/sql.py#L248-L251

This is more likely a typeshed issue rather than pyre. However I don't know the relation between the two and how experimental the use of LiteralString is. So I'm leaving this mostly as a FYI and in case you will want to propose something to typeshed.

Thank you very much!

**Comment by dvarrazzo** [comment] 2022-06-27 22:19
Please see the related issue https://github.com/psycopg/psycopg/issues/323 

The OP also opened a ticket to typeshed at https://github.com/python/typeshed/issues/8195

**Comment by stroxler** [comment] 2022-06-28 20:12
Thanks for letting us know!

At this point my guess is that Pyre won't need to do anything except bump our vendored typeshed stubs once the problem is fixed in upstream repositories, we ought to work out-of-the box against correct stubs. Feel free to ping us once that has been done, and if there are still problems we can circle back and figure out why.

**Comment by gbleaney** [comment] 2022-07-19 13:57
https://github.com/python/typeshed/pull/8268 is landed. @stroxler and chance of a typeshed upgrade + pyre release so we can close out this issue?

**Comment by craigfrancis** [comment] 2022-11-09 09:59
Would the typeshed upgrade allow "[from typing import LiteralString](https://pyre-check.org/play?input=%23!%2Fusr%2Fbin%2Fenv%20python3.11%0A%0Afrom%20typing%20import%20LiteralString%0A%0Adef%20run_sql(sql%3A%20typing.LiteralString%2C%20parameters%3A%20typing.List%5Bstr%5D%20%3D%20%5B%5D)%20-%3E%20None%3A%0A%20%20print(sql%2C%20%27%5Cn%27%2C%20parameters%2C%20%27%5Cn%27)%0A%0Arun_sql(%27WHERE%20name%20%3D%20%3F%27%2C%20%5Bname%5D)%0Arun_sql(%27WHERE%20name%20%3D%20%27%20%2B%20name)%20%23%20Wrong)" to work?

[PEP 675](https://peps.python.org/pep-0675/) implies should.

As a side note, "[import typing](https://pyre-check.org/play?input=%23!%2Fusr%2Fbin%2Fenv%20python3.11%0A%0Aimport%20typing%0A%0Adef%20run_sql(sql%3A%20typing.LiteralString%2C%20parameters%3A%20typing.List%5Bstr%5D%20%3D%20%5B%5D)%20-%3E%20None%3A%0A%20%20print(sql%2C%20%27%5Cn%27%2C%20parameters%2C%20%27%5Cn%27)%0A%0Arun_sql(%27WHERE%20name%20%3D%20%3F%27%2C%20%5Bname%5D)%0Arun_sql(%27WHERE%20name%20%3D%20%27%20%2B%20name)%20%23%20Wrong)" and "[from typing_extensions import LiteralString](https://pyre-check.org/play?input=%23!%2Fusr%2Fbin%2Fenv%20python3.11%0A%0Afrom%20typing%20import%20List%0Afrom%20typing_extensions%20import%20LiteralString%0A%0Adef%20run_sql(sql%3A%20LiteralString%2C%20parameters%3A%20List%5Bstr%5D%20%3D%20%5B%5D)%20-%3E%20None%3A%0A%20%20print(sql%2C%20%27%5Cn%27%2C%20parameters%2C%20%27%5Cn%27)%0A%0Arun_sql(%27WHERE%20name%20%3D%20%3F%27%2C%20%5Bname%5D)%0Arun_sql(%27WHERE%20name%20%3D%20%27%20%2B%20name)%20%23%20Wrong)" seem to work.

PS: I only have a basic understanding of Python.

**Comment by JelleZijlstra** [comment] 2022-11-09 20:17
`from typing import LiteralString` will work only if you are on Python 3.11 or higher. `from typing_extensions import LiteralString` works on all supported versions (3.7+).

**Comment by craigfrancis** [comment] 2022-11-10 11:29
Ahh, thanks @JelleZijlstra, it does work on my local machine (with 3.11); and I assume [https://pyre-check.org/play](https://pyre-check.org/play/) will be updated at some point in the future.

**Comment by yangdanny97** [comment] 2024-07-25 16:12
I think Pyre's typeshed has updated since then and I can see that LiteralString works in the playground so I'll close this

**Closed by yangdanny97** 2024-07-25 16:12 UTC
