### ISSUE TITLE
pyre segmentation fault

### ISSUE THREAD

**Issue by rpgoldman** [facebook/pyre-check#124] opened 2018-11-25 23:50 UTC
Like #119 I am getting error -11 when running pyre.  Following the instructions on that ticket, I ran with `pyre.bin`, hoping to get better error messages, but no luck:
```
$ pyre.bin check -debug -project-root `pwd` -workers 8 -typeshed lib/pyre_check/typeshed/ -search-path ~/Library/Python/3.6/lib/python/
2018-11-25 17:40:07 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-25 17:40:07 INFO Finding type stubs in `/Users/rpg/Library/Python/3.6/lib/python`...
2018-11-25 17:40:07 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/stdlib`...
2018-11-25 17:40:07 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/third_party`...
2018-11-25 17:40:07 INFO Finding external sources in `/Users/rpg/Library/Python/3.6/lib/python`...
2018-11-25 17:40:08 INFO Parsing 10123 stubs and external sources...
2018-11-25 17:40:18 WARNING Could not parse 21 external files due to syntax errors! Run with `--show-parse-errors` for more details.
2018-11-25 17:40:18 PERFORMANCE Stubs parsed: 10.924899s
2018-11-25 17:40:39 INFO Parsing 5425 sources in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-25 17:40:48 WARNING Could not parse 9 files due to syntax errors! Run with `--show-parse-errors` for more details.
2018-11-25 17:40:48 PERFORMANCE Sources parsed: 9.688026s
2018-11-25 17:40:58 PERFORMANCE Registered ignores: 9.318696s
2018-11-25 17:40:58 INFO Building type environment...
Segmentation fault: 11
```
If there's anything I can do to get a more informative error message, please let me know.
Note that despite the text of the `WARNING` method, `pyre.bin` errors when I give it `--show-parse-errors` as option.  Presumably this is only handled by the python wrapper?
Pyre version info
```
$ pyre.bin version
Darwin x86_64 @ Thu Oct 11 11:24:05 PDT 2018
601bfe35cfa2ce19e8dc3be4154922cf92af43c5
pyre version 0.0.16
```
Running on MacBookPro, High Sierra.

pyre is checking an _enormous_ number of files, because it's checking my virtual environment.  The parse errors all seem to be from there:
```
 ƛ Could not parse file at lib/python3.6/site-packages/pandas/core/arrays/base.py:204:0-204:0
          # type: () -> int
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/ipykernel/kernelapp.py:421:28-421:28
                         file=sys.stderr)
                             ^
 ƛ Could not parse file at lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:1:0-1:0
  ﻿#
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/pandas/core/base.py:798:0-798:0
          # type: () -> np.ndarray
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/xarray/core/computation.py:162:0-162:0
      # type: (...) -> List[OrderedDict[Any, Variable]]
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/mypy/typeshed/tests/check_consistent.py:37:43-37:43
      for file1, *others in consistent_files:
                                            ^
 ƛ Could not parse file at lib/python3.6/site-packages/jedi/_compatibility.py:368:16-368:16
          print >> sys.stderr, args
                 ^
 ƛ Could not parse file at lib/python3.6/site-packages/arviz/plots/forestplot.py:460:51-460:51
          end_y = max(y for y, *_ in self.iterator())
                                                    ^
 ƛ Could not parse file at lib/python3.6/site-packages/arviz/data/io_cmdstan.py:181:48-181:48
                  for sample, *_ in parsed_output:
                                                 ^
 ƛ Could not parse 9 files due to syntax errors!
```
some of these look pretty dubious as syntax errors.  For example, the ipykernel block with the syntax errors is the following:
``` python
            def print_tb(etype, evalue, stb):
                print ("GUI event loop or pylab initialization failed",
                       file=sys.stderr)
                print (shell.InteractiveTB.stb2text(stb), file=sys.stderr)
```

**Comment by dark** [comment] 2018-11-26 19:53
Thanks for the report.
Syntax errors and segmentation faults are two unrelated problems; the former will not cause the latter.

Can you please try and re-run pyre with `--debug` to try and see if more information is printed? It might not work due a current limitation of what information we print (I am working on it), but it's worth giving it a shot.

If the above does not work, could you please try and selectively add directories to the search path from the virtual enviroment, one at a time, to see on which file/module pyre starts crashing on? That would help narrow down the issue.

**Comment by rpgoldman** [comment] 2018-11-26 21:15
Sorry -- do you want me to run `pyre` or `pyre.bin` with debug?  The output I showed was from `pyre.bin` with the `-debug` flag, and `pyre` doesn't seem to have one.
I tried `pyre check --verbose`, but after an hour and 10 minutes, it's still parsing, so that won't work...

**Comment by dark** [comment] 2018-11-26 21:18
My bad, I did not realize that the command was run with `--debug` already.
Then that output will not help us identify the issue yet.

If that's feasible, could you please try my latest suggestion? Otherwise the next release of Pyre will have more debug info that will help us troubleshoot the problem further.

**Comment by rpgoldman** [comment] 2018-11-26 21:32
One bit of information: I moved aside all the virtualenv contents, and `pyre.bin` *still* got a segfault.
Second bit of information: I restored the virtualenv files, moved my `stubs/` directory (with my own stubs for PyMC3, itertools, and a few others) and `pyre.bin` still got a segfault.  So it's blowing up on something in my own source code.  More as I have it.

**Comment by rpgoldman** [comment] 2018-11-27 17:30
No joy, I'm afraid:
```
$ ./bin/pyre.bin check -debug -project-root `pwd` -workers 8 -typeshed lib/pyre_check/typeshed/
2018-11-27 11:27:59 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-27 11:27:59 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/stdlib`...
2018-11-27 11:27:59 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/third_party`...
2018-11-27 11:27:59 INFO Parsing 2592 stubs and external sources...
2018-11-27 11:28:01 PERFORMANCE Stubs parsed: 1.428321s
2018-11-27 11:28:02 INFO Parsing 5411 sources in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-27 11:28:10 WARNING Could not parse 9 files due to syntax errors! Run `pyre --show-parse-errors check` for more details.
2018-11-27 11:28:10 PERFORMANCE Sources parsed: 7.792732s
2018-11-27 11:28:18 PERFORMANCE Registered ignores: 8.150550s
2018-11-27 11:28:18 INFO Building type environment...
Segmentation fault: 11
```
The above is with only one python file actually in this directory, but all of the stubs and the virtualenv files.

**Comment by dark** [comment] 2018-11-28 02:47
The next version of Pyre will print more info when such a crash occurs.

In the meantime, though, I noticed another oddity. You have only one file in `pwd`, but Pyre prints that:
```
2018-11-27 11:28:02 INFO Parsing 5411 sources in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
```
This is likely because there are other directories in there, so the issue might be caused by one of them.

**Comment by rpgoldman** [comment] 2018-11-28 03:32
> The next version of Pyre will print more info when such a crash occurs.
> 
> In the meantime, though, I noticed another oddity. You have only one file in `pwd`, but Pyre prints that:
> 
> ```
> 2018-11-27 11:28:02 INFO Parsing 5411 sources in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
> ```
> This is likely because there are other directories in there, so the issue might be caused by one of them.


There are actually 15 `*.py` files in there now (moved back from the attic directory where I deposited them).
But you are right, all told, the following command line indicates that there are 7424 files reachable from there:
```
find . \( -name '.git' -prune \) -o \( \( -name '*.py' -o -name '*.pyi' \) -print \) | wc -l
```
So `pyre` really seems like it needs a *full* ignore configuration option, instead of just a "skip reporting" option.
I'm pretty much a n00b at Python, so this isn't an enormous project (only 2300 lines of code), but it has a big dependency tail.
IIUC, pyre is parsing and checking all of `numpy`, `pandas`, `pymc3`, `zmq`, `mypy`, and `ipython` -- and all the typeshed that `mypy` carries with it! -- because of the virtualenv.
I'm not sure if this means I'm doing something wrong, or if the pyre team just hasn't been considering virtualenv's in its use case.

**Comment by dark** [comment] 2018-11-28 22:35
A new version of Pyre has been released. Running pyre with `--debug` should show more information.

**Comment by rpgoldman** [comment] 2018-11-28 22:42
Yes!  That did it!  Here's the informative error message:
```
2018-11-28 16:40:17 ERROR Order is cyclic:
Trace: lib.python3.6.site-packages.qtconsole.rich_jupyter_widget.RichIPythonWidget -> lib.python3.6.site-packages.qtconsole.jupyter_widget.JupyterWidget -> lib.python3.6.site-packages.qtconsole.jupyter_widget.IPythonWidget -> lib.python3.6.site-packages.qtconsole.jupyter_widget.JupyterWidget
Uncaught exception:
  
  Analysis__TypeOrder.Cyclic

Raised at file "format.ml" (inlined), line 242, characters 35-52
Called from file "format.ml", line 469, characters 8-33
Called from file "format.ml", line 484, characters 6-24
```

**Comment by dark** [comment] 2018-11-28 22:47
This is the same of #119 then, due to the `qtconsole` sources. I will close this issue, and we will keep tracking the proper resolution in that issue.

For now, as a workaround, you can use the newly introduced `exclude` option (either in the config file, or on the commandline) to prevent pyre from parsing the `qtconsole` directory. Since it's a regexp, `.*/qtconsole/.*` should suffice.

Thanks again for the detailed report!

**Comment by rpgoldman** [comment] 2018-11-28 23:41
This is one of those "good news and bad news" things.  The good news is that the following works without erroring out:
```
./bin/pyre.bin check -debug -project-root `pwd` -workers 8 -typeshed lib/pyre_check/typeshed/ -exclude '.*/qtconsole/.*'
```
The bad news is that it hangs at this point:
```
2018-11-28 17:17:44 PROGRESS Processed 4950 of 5375 sources
2018-11-28 17:17:44 PROGRESS Processed 5000 of 5375 sources
2018-11-28 17:17:45 PROGRESS Processed 5075 of 5375 sources
2018-11-28 17:17:47 PROGRESS Processed 5150 of 5375 sources
2018-11-28 17:17:53 PROGRESS Processed 5225 of 5375 sources
2018-11-28 17:17:53 PROGRESS Processed 5300 of 5375 sources
```
No further output for 25 minutes (approximately).

**Comment by rpgoldman** [comment] 2018-11-28 23:54
Also, could you speak to what the form of the `exclude` arguments should be?  I was trying to put the regexp you provided in the `.pyre_configuration` file, but it didn't seem to work.  I *was* able to use it successfully in the `pyre.bin` command line.  I conjecture that the python script might need to do something to make sure that the regexps are quoted properly when they are passed to `pyre.bin`, but I could be wrong about that.

**Comment by dark** [comment] 2018-11-29 00:03
Both forms - config file and commandline - should be equivalent. How did it fail?

Could you please provide the full output of the debug run as well?

**Comment by rpgoldman** [comment] 2018-11-29 02:35
You are right; I must have made a mistake in the syntax.  All seems to be well now, thanks.

May I ask just one more question: what should we be doing with these very large libraries (numpy, etc.) for which there are no stubs?  Is this what the `ignore_all_errors` is intended for?  So that pyre can *see* those library files and use information from them to report errors in *our* code, without swamping us with error messages from code that was not well-typed (in pyre's more restrictive sense)?

**Comment by dark** [comment] 2018-11-29 16:09
Pyre will not emit warnings for functions that are not annotated, to support gradual typing: https://pyre-check.org/docs/gradual-typing.html
So, there is no need to use `ignore_all_errors` on unannotated third-party libraries.

**Closed by dark** 2018-11-29 16:09 UTC
Labels: need-info
